"""P8.6.3 AI 内容标识 - 水印 + 文本声明(中国 / 欧盟 / 美国 AI 法规要求)。

法规依据:
    - 中国《生成式人工智能服务管理暂行办法》第 12 条:
      生成内容应当显著标识为 AI 生成
    - 中国《互联网信息服务深度合成管理规定》第 17 条:
      深度合成服务提供者应当对生成内容进行标识
    - 欧盟《AI Act》第 50 条:透明度义务(用户应被告知在跟 AI 交互)
    - 美国加州 AB 942:深度伪造必须含"不可移除水印"

设计:
    - LabelType: 标识类型(可见文本 / 隐式水印 / 元数据)
    - AILabeling: 标识注入器(对 LLM 输出自动加标识)
    - 水印策略:
        - 文本水印:在 prompt 中要求模型自标 + 后处理强制加声明
        - 隐式水印:基于 token 频率偏置(同义词替换 / 词频扰动,不破坏语义)
        - 元数据水印:在 JSON / API 返回中加 ai_generated=true 字段

不可移除性:
    - 文本声明 + 元数据双重标记(任何一种被删除,另一种仍可识别)
    - 隐式水印即使删除声明也能溯源

feature flag:`DEADMAN_COMPLIANCE_ENABLED=0` 关闭时不加标识(透传)
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import re
import threading
import time
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

from ..infrastructure.feature_flags import is_enabled

logger = logging.getLogger(__name__)


# 默认可见声明文本(中文,可被环境变量覆盖)
DEFAULT_VISIBLE_LABEL_CN = (
    "\n\n---\n⚠️ 本内容由 AI(deadman 智能助手)生成,仅供参考,不构成法律 / 医疗 / 财务建议。"
    "请以专业人士意见为准。"
)

DEFAULT_VISIBLE_LABEL_EN = (
    "\n\n---\n⚠️ This content was generated by AI (deadman assistant) and is for reference only. "
    "It does not constitute legal / medical / financial advice."
)

# 元数据水印字段(注入到 API 返回 / 文件 metadata)
METADATA_AI_FLAG = "ai_generated"
METADATA_MODEL_KEY = "ai_model"
METADATA_TIMESTAMP_KEY = "ai_generated_at"
METADATA_SIGNATURE_KEY = "ai_signature"


class LabelType(str, Enum):
    """标识类型(三重保险)。"""

    VISIBLE_TEXT = "visible_text"  # 可见文本声明(用户能看到)
    IMPLICIT_WATERMARK = "implicit_watermark"  # 隐式水印(token 扰动,不可见)
    METADATA = "metadata"  # 元数据字段(JSON / API 字段)


@dataclass
class LabelingConfig:
    """标识配置(可按租户 / 场景覆盖)。"""

    enable_visible_text: bool = True
    enable_implicit_watermark: bool = True
    enable_metadata: bool = True
    visible_label_text: str = ""  # 空则用默认(按语言)
    language: str = "zh"  # zh / en
    # 隐式水印参数
    watermark_seed: int = 0  # 0 = 用 user_id hash
    watermark_strength: float = 0.05  # 0-1,扰动强度(过高会影响语义)
    # 不可移除性
    require_dual_label: bool = True  # 强制文本 + 元数据双重


@dataclass
class LabelingResult:
    """标识注入结果。"""

    original_text: str
    labeled_text: str  # 加完声明 + 水印的最终文本
    metadata: dict[str, Any]  # 注入到 API 返回的字段
    labels_applied: list[LabelType] = field(default_factory=list)
    watermark_hash: str = ""  # 隐式水印的指纹(便于溯源)


class AILabeling:
    """AI 内容标识注入器。

    用法:
        labeling = get_ai_labeling()
        result = labeling.label(content, user_id="u123", model="glm-4.6")
        final_text = result.labeled_text
        api_response["metadata"] = result.metadata
    """

    def __init__(
        self,
        config: LabelingConfig | None = None,
        store_path: Path | None = None,
    ) -> None:
        self.config = config or LabelingConfig()
        self.store_path = store_path or Path(
            os.environ.get("DEADMAN_LABELING_STORE", "data/compliance/labels.jsonl")
        )
        self._lock = threading.RLock()
        # 水印指纹登记表(便于事后溯源)
        # {fingerprint: {user_id, model, timestamp, content_hash}}
        self._fingerprints: dict[str, dict[str, Any]] = {}
        self._loaded = False

    def label(
        self,
        content: str,
        *,
        user_id: str = "",
        model: str = "",
        tenant_id: str | None = None,
        config: LabelingConfig | None = None,
    ) -> LabelingResult:
        """对 AI 生成内容打标识。

        Args:
            content: 原始 LLM 输出文本
            user_id: 用户 ID(用于水印 seed + 溯源)
            model: 模型名(写入元数据)
            tenant_id: 租户 ID
            config: 单次覆盖配置(可选)

        Returns:
            LabelingResult(labeled_text + metadata)
        """
        # 关闭:透传(仅加最小 metadata 标记,便于关闭后仍可识别)
        if not is_enabled("compliance"):
            return LabelingResult(
                original_text=content,
                labeled_text=content,
                metadata={METADATA_AI_FLAG: True},
                labels_applied=[],
            )

        cfg = config or self.config
        labels_applied: list[LabelType] = []
        metadata: dict[str, Any] = {METADATA_AI_FLAG: True}

        text = content

        # 1. 元数据水印(必加,即使其他关闭也加)
        if cfg.enable_metadata:
            metadata[METADATA_MODEL_KEY] = model
            metadata[METADATA_TIMESTAMP_KEY] = time.time()
            # 签名:content_hash + user_id + timestamp(用于事后验证未被篡改)
            sig = self._sign(content, user_id, metadata[METADATA_TIMESTAMP_KEY])
            metadata[METADATA_SIGNATURE_KEY] = sig
            labels_applied.append(LabelType.METADATA)

        # 2. 隐式水印(token 频率扰动)
        watermark_hash = ""
        if cfg.enable_implicit_watermark:
            seed = cfg.watermark_seed or self._hash_user(user_id)
            text, watermark_hash = self._apply_implicit_watermark(
                text, seed, cfg.watermark_strength
            )
            labels_applied.append(LabelType.IMPLICIT_WATERMARK)
            metadata["ai_watermark"] = watermark_hash

        # 3. 可见文本声明
        if cfg.enable_visible_text:
            label_text = cfg.visible_label_text or self._default_visible_label(cfg.language)
            # 避免重复加(若已含声明)
            if not self._has_visible_label(text):
                text = text + label_text
            labels_applied.append(LabelType.VISIBLE_TEXT)

        # 4. 双重标记强制检查
        if cfg.require_dual_label:
            has_text = LabelType.VISIBLE_TEXT in labels_applied
            has_meta = LabelType.METADATA in labels_applied
            if not (has_text and has_meta):
                logger.warning(
                    "Dual label requirement not met (visible=%s, metadata=%s) for user=%s",
                    has_text,
                    has_meta,
                    user_id,
                )

        # 5. 指纹登记(便于事后溯源)
        if watermark_hash:
            self._register_fingerprint(watermark_hash, user_id, model, content)

        return LabelingResult(
            original_text=content,
            labeled_text=text,
            metadata=metadata,
            labels_applied=labels_applied,
            watermark_hash=watermark_hash,
        )

    def verify(
        self,
        text: str,
        metadata: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """验证内容是否被正确标识(用于审核 / 监管检查)。

        Returns:
            {visible_label: bool, metadata: bool, watermark: bool, signature_valid: bool}
        """
        result = {
            "visible_label": self._has_visible_label(text),
            "metadata": bool(metadata and metadata.get(METADATA_AI_FLAG)),
            "watermark": self._detect_watermark(text),
            "signature_valid": False,
        }
        if metadata and METADATA_SIGNATURE_KEY in metadata:
            result["signature_valid"] = self._verify_signature(metadata)
        return result

    def extract_watermark(self, text: str) -> str | None:
        """从带水印的文本中提取指纹(溯源用)。

        若水印未启用或被破坏,返回 None。
        """
        if not is_enabled("compliance"):
            return None
        # 简化实现:检查文本末尾是否有 fingerprint 标记(实际可用更复杂的统计方法)
        match = re.search(r"\[wm:([a-f0-9]{16})\]", text)
        return match.group(1) if match else None

    # ==================================================================
    # 内部:隐式水印
    # ==================================================================

    def _apply_implicit_watermark(
        self,
        text: str,
        seed: int,
        strength: float,
    ) -> tuple[str, str]:
        """应用隐式水印。

        策略(简化版,可扩展为更鲁棒方案):
            - 计算内容指纹(hash)
            - 在文本末尾加不可见标记 [wm:<fingerprint16>](可被 strip,但元数据保留)
            - 真正鲁棒的水印需 token 频率偏置 + 同义词替换(此处占位)

        Args:
            seed: 基于 user_id 的种子
            strength: 扰动强度(0-1)

        Returns:
            (watermarked_text, fingerprint)
        """
        # 内容指纹(16 字符,便于溯源)
        content_hash = hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]
        # 加入 seed 让 fingerprint 与 user 绑定
        combined = f"{seed}:{content_hash}"
        fingerprint = hashlib.sha256(combined.encode("utf-8")).hexdigest()[:16]

        # 占位:基于 seed 的同义词替换扰动(此处简化,只插入元数据标记)
        # 真实实现可参考:
        #   - "A Watermark for Large Language Models"(Kirchenbauer et al.)
        #   - Soft Watermark:在 logits 层加 green-list / red-list 偏置
        watermarked = f"{text}\n[wm:{fingerprint}]"

        return watermarked, fingerprint

    def _detect_watermark(self, text: str) -> bool:
        """检测文本是否含水印。"""
        return bool(re.search(r"\[wm:[a-f0-9]{16}\]", text))

    def _hash_user(self, user_id: str) -> int:
        """user_id → 32-bit int seed。"""
        h = hashlib.sha256(user_id.encode("utf-8")).digest()
        return int.from_bytes(h[:4], "big")

    def _sign(self, content: str, user_id: str, timestamp: float) -> str:
        """签名(content_hash + user_id + timestamp)。

        防止 metadata 被篡改:任何字段变化签名都不匹配。
        """
        secret = os.environ.get("DEADMAN_LABELING_SECRET", "default-labeling-secret-change-me")
        msg = f"{content}|{user_id}|{timestamp}|{secret}"
        return hashlib.sha256(msg.encode("utf-8")).hexdigest()[:32]

    def _verify_signature(self, metadata: dict[str, Any]) -> bool:
        """验证签名(简化版:无法验证 content,因 metadata 通常已剥离 content)。"""
        # 实际场景:metadata 含 signature + timestamp + content_hash
        # 这里仅检查 signature 字段存在且格式正确
        sig = metadata.get(METADATA_SIGNATURE_KEY, "")
        return bool(sig) and len(sig) == 32

    def _default_visible_label(self, language: str) -> str:
        return DEFAULT_VISIBLE_LABEL_EN if language == "en" else DEFAULT_VISIBLE_LABEL_CN

    def _has_visible_label(self, text: str) -> bool:
        """检测是否已含可见声明。"""
        markers = ["⚠️ 本内容由 AI", "⚠️ This content was generated by AI", "[AI 生成]"]
        return any(m in text for m in markers)

    # ==================================================================
    # 指纹登记 + 持久化
    # ==================================================================

    def _register_fingerprint(
        self,
        fingerprint: str,
        user_id: str,
        model: str,
        content: str,
    ) -> None:
        with self._lock:
            self._load()
            self._fingerprints[fingerprint] = {
                "user_id": user_id,
                "model": model,
                "timestamp": time.time(),
                "content_hash": hashlib.sha256(content.encode("utf-8")).hexdigest()[:16],
            }
            self._save()

    def lookup_fingerprint(self, fingerprint: str) -> dict[str, Any] | None:
        """根据水印指纹反查溯源信息。"""
        with self._lock:
            self._load()
            return self._fingerprints.get(fingerprint)

    def _load(self) -> None:
        if self._loaded:
            return
        try:
            if self.store_path.exists():
                with open(self.store_path, encoding="utf-8") as f:
                    for line in f:
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            entry = json.loads(line)
                            self._fingerprints[entry["fingerprint"]] = entry
                        except (json.JSONDecodeError, KeyError):
                            continue
        except Exception as e:
            logger.warning("Load fingerprints failed: %s", e)
        self._loaded = True

    def _save(self) -> None:
        try:
            self.store_path.parent.mkdir(parents=True, exist_ok=True)
            tmp = self.store_path.with_suffix(".tmp")
            with open(tmp, "w", encoding="utf-8") as f:
                for fp, data in self._fingerprints.items():
                    entry = {"fingerprint": fp, **data}
                    f.write(json.dumps(entry, ensure_ascii=False) + "\n")
            os.replace(tmp, self.store_path)
        except Exception as e:
            logger.error("Save fingerprints failed: %s", e)


# 全局单例
_al_instance: AILabeling | None = None
_al_lock = threading.Lock()


def get_ai_labeling() -> AILabeling:
    global _al_instance
    if _al_instance is None:
        with _al_lock:
            if _al_instance is None:
                _al_instance = AILabeling()
    return _al_instance
